### ISSUE TITLE
Custom arm64 kernel build won't boot

### ISSUE THREAD

**Issue by remusmp** [kdoren/linux#14]
Hello,

Trying to figure out what I'm doing wrong :) I have a repo with all files here: https://github.com/remusmp/rpi-rt-kernel

Here's how I build the kernel (with docker):
```
FROM ubuntu:20.04

ENV TZ=Europe/Copenhagen
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update
RUN apt-get install -y git make gcc bison flex libssl-dev bc ncurses-dev kmod
RUN apt-get install -y crossbuild-essential-arm64
RUN apt-get install -y wget zip unzip fdisk nano

WORKDIR /rpi-kernel
RUN git clone https://github.com/kdoren/linux.git -b rpi-5.10.52-rt --depth=1

WORKDIR /rpi-kernel/linux/
ENV KERNEL=kernel8
ENV ARCH=arm64
ENV CROSS_COMPILE=aarch64-linux-gnu-

RUN make bcm2711_defconfig

ADD .config ./
RUN make Image modules dtbs

WORKDIR /raspios
RUN apt -y install 
RUN wget https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip
RUN unzip 2021-05-07-raspios-buster-armhf-lite.zip && rm 2021-05-07-raspios-buster-armhf-lite.zip
RUN mkdir /raspios/mnt && mkdir /raspios/mnt/disk && mkdir /raspios/mnt/boot
ADD build.sh ./
ADD config.txt ./
```

I get my .config file in the following way: run the container, then `make menuconfig`, disable KVM, enable Fully Preemptible RT, exit and save. Then I copy the `.config` file from the container. I don't do any other customization of the kernel.

I would also like to have everything in an SD card image so I got this `build.sh` script, which takes the raspios lite image and configures it to use the new kernel:
```
#!/bin/sh

mount -t ext4 -o loop,offset=$((532480*512)) 2021-05-07-raspios-buster-armhf-lite.img /raspios/mnt/disk
mount -t vfat -o loop,offset=$((8192*512)),sizelimit=$((524288*512)) 2021-05-07-raspios-buster-armhf-lite.img /raspios/mnt/boot

cd /rpi-kernel/linux/
make INSTALL_MOD_PATH=/raspios/mnt/disk modules_install
make INSTALL_DTBS_PATH=/raspios/mnt/boot dtbs_install
cd -

cp /rpi-kernel/linux/arch/arm64/boot/Image /raspios/mnt/boot/$KERNEL\_rt.img
cp /rpi-kernel/linux/arch/arm64/boot/dts/broadcom/*.dtb /raspios/mnt/boot/
cp /rpi-kernel/linux/arch/arm64/boot/dts/overlays/*.dtb* /raspios/mnt/boot/overlays/
cp /rpi-kernel/linux/arch/arm64/boot/dts/overlays/README /raspios/mnt/boot/overlays/

cp /raspios/config.txt /raspios/mnt/boot/
touch /raspios/mnt/boot/ssh

umount /raspios/mnt/disk
umount /raspios/mnt/boot

zip 2021-05-07-raspios-buster-armhf-lite.zip 2021-05-07-raspios-buster-armhf-lite.img
```

Still it won't boot the new kernel. Just getting a blank screen.

**Comment by kdoren** [comment]
I don't build in docker container so i can't comment on that part but it sounds like it's working.
I haven't posted a release yet, but you can build from my branch rpi-5.10.59-rt which is more current.
For 64-bit I CROSS_COMPILE and build on 32-bit raspian.  I have a recent post under discussions about this.
My preference is to build .deb package and install that, then copy files from install location to sd card.  However installing 64-bit deb package on 32-bit system requires "dpkg --add-architecture arm64" which in turn requires editing your apt sources to use "deb [ arch=armhf ] " so they don't look for 64-bit packages except for kernel repo.

To boot 64-bit kernel, /boot/config.txt needs to contain "arm_64bit=1"
You also need to copy the system files to /lib/

I make iso images with multiple kernels so I can compare.  I don't replace the standard kernel, I have sections in config.txt that can be enabled to select an alternate kernel.

To build deb package:
```
make bindeb-pkg
```

to install from arm64 deb package:
```
# if installing 64-bit kernel on 32-bit system:
# dpkg --add-architecture arm64
# sed -i 's|^deb http|deb [ arch=armhf ] http|g' /etc/apt/sources.list
# sed -i 's|^deb http|deb [ arch=armhf ] http|g' /etc/apt/sources.list.d/raspi.list
apt install ./linux-image-5.10.59-rt51-v8+_5.10.59-1_arm64.deb
KERN=5.10.59-rt51-v8+
mkdir -p /boot/$KERN/overlays/
cp -d /usr/lib/linux-image-$KERN/overlays/* /boot/$KERN/overlays/
[[ -d /usr/lib/linux-image-$KERN/broadcom ]] && cp -d /usr/lib/linux-image-$KERN/broadcom/* /boot/$KERN/
touch /boot/$KERN/overlays/README
mv /boot/vmlinuz-$KERN /boot/$KERN/
mv /boot/System.map-$KERN /boot/$KERN/
cp /boot/config-$KERN /boot/$KERN/
cat >> /boot/config.txt << EOF

[all]
kernel=vmlinuz-$KERN
# initramfs initrd.img-$KERN
os_prefix=$KERN/
overlay_prefix=overlays/
$(if [[ "$KERN" =~ 'v8' ]]; then echo 'arm_64bit=1'; fi)
[all]
EOF
```

I previously built and installed the non-deb way from tgz files.  When you run "make modules_install" and "make dtbs_install", make copies the required files into $INSTALL_MOD_PATH and $INSTALL_DTBS_PATH, so that is where you should pick up the files.

This isn't completely tested, but I think build/install of 64-bit kernel from tgz looks like this:
```
KERN=5.10.59-rt51-v8+
export ARCH=arm
export CROSS_COMPILE=/opt/aarch64/bin/aarch64-linux-gnu-
export KERNEL=kernel8
make bcm2711_defconfig
make menuconfig
make -j4 Image modules dtbs
export INSTALL_MOD_PATH=../$KERN
export INSTALL_DTBS_PATH=../$KERN
mkdir -p ../$KERN
make modules_install
make dtbs_install
cp ./arch/arm64/boot/Image $INSTALL_MOD_PATH/vmlinuz-$KERN
cd $INSTALL_MOD_PATH
tar czf ../linux-image-$KERN.tgz *
# make bindeb-pkg   # if you want deb package

# To install from tgz file on target system:
KERN=5.10.59-rt51-v8+
mkdir linux-image-$KERN
tar xzf linux-image-$KERN.tgz -C linux-image-$KERN/

# copy kernel files to correct locations
mkdir -p /boot/$KERN/overlays
cd linux-image-$KERN
cp -d overlays/* /boot/$KERN/overlays/
cp -d broadcom/bcm* /boot/$KERN/
cp  vmlinuz-$KERN /boot/$KERN/
cp -dr lib/* /lib/
touch /boot/$KERN/overlays/README

cat >> /boot/config.txt << EOF

[all]
kernel=vmlinuz-$KERN
os_prefix=$KERN/
overlay_prefix=overlays/
arm_64bit=1
[all]
EOF
```
Then reboot

**Comment by kdoren** [comment]
@remusmp FYI I just posted a release of 5.10.59-rt51, and included both 32-bit and 64-bit deb packages.
https://github.com/kdoren/linux/releases/tag/rpi_5.10.59-rt51

**Comment by remusmp** [comment]
@kdoren Thanks a lot! I will give them a try. As far as I can see I am missing `arm_64bit=1` from `config.txt`. I will test that very soon and return with an update.
I am trying to use docker for builds because I am building with a gitlab pipeline on Kubernetes.

**Comment by remusmp** [comment]
Yep, it works. I was missing `arm_64bit=1` in `config.txt`. Thanks for the above, I wouldn't have spot the error without it :)
