### ISSUE TITLE
Kernel won't boot on Raspi OS 2022-01-28

### ISSUE THREAD

**Issue by ojjo** [kdoren/linux#21]
Hello,

I tried to install `5.10.74-rt54-v7l+` kernel `.deb` on a RPi4, Raspberry pi OS 32bits bullseye (2022-01-28). Got this message after reboot: `cpu cpu0 : cannot get clock for CPU0`. Same problem with `5.10.74-rt54-v8+` kernel on 64bits OS. Works with the 2021-05-28 Raspberry pi OS release. 

Is there specific installation instructions for the last Raspi OS release?

Thanks

**Comment by kdoren** [comment]
@ojjo This discussion looks relevant:  https://github.com/raspberrypi/firmware/issues/1688

Try disabling the vc4 driver (comment out in /boot/config.txt), and/or a firmware update

**Comment by ojjo** [comment]
With firmware update, Kernel start but each boot I get a message below the taskbar: `Failed to open command line file '5.10.74-rt54-v7l+/cmdline.txt'`
And booting the low latency kernel, I noticed the cpu governor is set to `ondemand`

**Comment by kdoren** [comment]
@ojjo Thanks for reporting.  My kernel install script doesn't copy cmdline.txt to /boot/{$KERN}, but it should (docs clearly say it looks there).  It must use /boot/cmdline.txt if it can't find it there.  I'll change my install instructions to place a copy there.

The llat kernel was definitely built with default cpufreq governor "performance":
```
pi@jambox:~ $ grep CPU_FREQ_DEFAULT_GOV /boot/5.10.74-llat-v7l+/config-5.10.74-llat-v7l+
CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y
# CONFIG_CPU_FREQ_DEFAULT_GOV_POWERSAVE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_CONSERVATIVE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL is not set
```
That should be the default.  I can't explain why you're getting "ondemand", unless something is overriding.
First check to make sure in really booted to the llat kernel. (maybe it failed because cmdline.txt was not there?)
```
pi@jambox:~ $ uname -r
5.10.74-rt54-v7l+
pi@jambox:~ $ cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
performance
performance
performance
performance
```

In my Jambox image, "performance" is also forced at boot time by this systemd service:
https://github.com/kdoren/jambox-pi-gen/blob/jambox/stage3/02-misc-config2/files/cpu_performance_scaling_governor.service
But that should not be required if you are really booting a kernel with "performance" set as default. 

You can probably make the cmdline.txt warning go away with:
```
sudo cp /boot/cmdline.txt /boot/5.10.74-rt54-v7l+/
# and/or
sudo cp /boot/cmdline.txt /boot/5.10.74-llat-v7l+/
```

**Comment by kdoren** [comment]
@ojjo I tried the 5.10.74-llat kernel under raspian buster and cpufreq governor worked as expected.  default was correct even when I disabled the systemd service mentioned above.
However with same kernel under latest raspian bullseye, cpufreq governor did not work.  It was not even visible for me.

I built a 5.15.21-llat kernel.  cpufreq governor was visible but defaulted to ondemand, as you reported.  I'll post a release of it soon.

There are very recent reports of cpufreq governor problems under bullseye.
https://github.com/raspberrypi/linux/issues/4875

The reported problems are not identical, but do indicate bugs in this area,

**Comment by ojjo** [comment]
Thanks for your support !

cmdline.txt warning goes away with your command.

I've downloaded raspios buster (2020-05-27 and 2021-05-07) to try the 5.10.74-llat-v7l+, but the result was the same (except debian version):

```
pi@raspberrypi:~ $ cat /etc/debian_version
10.4
pi@raspberrypi:~ $ uname -r
5.10.74-llat-v7l+
pi@raspberrypi:~ $ cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
ondemand
ondemand
ondemand
ondemand
```

I don't know if it's relevant, but this script https://github.com/raboof/realtimeconfigquickscan always gives these warnings (independently of RPi OS release or PREEMPT / real time kernel)

```
Checking kernel support for high resolution timers... Could not find kernel configuration - undetermined
Kernel with Real-Time Preemption... Could not find kernel configuration - undetermined
Checking if kernel system timer is high-resolution... Could not find kernel configuration - undetermined
Checking kernel support for tickless timer... Could not find kernel configuration - undetermined
```
The python version:
```
[ WARNING ] Could not find kernel configuration.

Traceback (most recent call last):
  File "/home/pi/rtcqs/./rtcqs.py", line 537, in <module>
    main()
  File "/home/pi/rtcqs/./rtcqs.py", line 524, in main
    high_res_timers_check()
  File "/home/pi/rtcqs/./rtcqs.py", line 202, in high_res_timers_check
    if 'CONFIG_HIGH_RES_TIMERS=y' not in kernel['config']:
KeyError: 'config'
```

**Comment by kdoren** [comment]
@ojjo  realtimeconfigquickscan is looking for either /proc/config.gz or /boot/config-`uname -r` 
My install instructions move that file to /boot/`uname -r`/   (I just changed to copy instead of move).

you could either copy it back:
```
sudo cp /boot/`uname -r`/config-`uname -r` /boot/
```
or generate a copy of /proc/config.gz:
```
sudo modprobe configs
```

**Comment by kdoren** [comment]
@ojjo It turns out that Raspberry Pi OS has a service that runs at startup which sets the performance governor to on-demand.  So it overrides the kernel default.  This service is called raspi-config (no relation to the raspi-config program), and can be disabled.  I wrote up a wiki page on how to do that.

https://github.com/kdoren/linux/wiki/Performance-Governor-settings

**Comment by ojjo** [comment]
I tried the 5.10.95-llat kernel, works fine. Thanks !

**Comment by kdoren** [comment]
@ojjo It turns out that copying cmdline.txt into /boot/$KERN can cause problems in some cases, especially on a system that has not been booted yet.  This is because there are things that can edit /boot/cmdline.txt which don't know about the other copies (like raspi-config).  

The vfat volume format of /boot does not support symbolic links.  So I think the safest thing to do is to only have one copy, /boot/cmdline.txt, and live with the warning.  I'll see if there is a way to disable the warning.
