### ISSUE TITLE
typo on the wiki

### ISSUE THREAD

**Issue by SebKuzminsky** [kdoren/linux#28]
### Describe the bug

Hi there, thanks for this great resource.

I think there's a typo on the wiki, on the [Installation of kernel from deb package (Raspberry Pi OS)](https://github.com/kdoren/linux/wiki/Installation-of-kernel-from-deb-package-%28Raspberry-Pi-OS%29) page.  Down in the command block, in the section where it modifies `/boot/config.txt`, it has this line:

`overlay_prefix=o/$(if [[ "$KERN" =~ 'v8' ]]; then echo -e "\narm_64bit=1"; fi)`

I think there should be a newline after `overlay_prefix=o/`, before `$(if [[ "$KERN" ...`

### Steps to reproduce the behaviour

n/a

### Device (s)

Other

### System

n/a

**Comment by kdoren** [comment]
@SebKuzminsky Thanks for posting.  
That code is intentional, but probably too obscure.
In a single line of cat command, it works with both 32 and 64-bit kernels, and avoids an extra blank line in case of 64-bit kernel.
The newline is before "arm_64bit" and is only there if needed,

32-bit kernel (KERN does not contain "v8"):
```
pi@jambox:~ $ cat << EOF
overlay_prefix=o/$(if [[ "$KERN" =~ 'v8' ]]; then echo -e "\narm_64bit=1"; fi)
EOF
```
results:
```
overlay_prefix=o/
```
    
    
64-bit kernel (KERN contains "v8"):
```
pi@jambox:~ $ cat << EOF
overlay_prefix=o/$(if [[ "$KERN" =~ 'v8' ]]; then echo -e "\narm_64bit=1"; fi)
EOF
```
results:
```
overlay_prefix=o/
arm_64bit=1
```

**Comment by SebKuzminsky** [comment]
Ah, I missed that - too clever for me ;-)
In any case, thanks for this project, it's super handy to have a Preempt-RT kernel deb available for the Raspberry Pi!
